-- Exploratory Data Analysis (EDA)
/*
1) Database Exploration 
2) Dimension Exploration
3) Date Exploration
4) Measures Exploration
5) Magnitude
6) Ranking (Top N - Bottom N)
*/

-- 1) Database Exploration
-- Exploring all objects in the database
SELECT
* 
FROM INFORMATION_SCHEMA.TABLES

-- Explore all columns in the database
SELECT
* 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'dim_customers'

-- 2) Dimensions Exploration
-- Identifying the unique values (or categories) in each dimension.
-- Recognizing how data might be grouped or segmented , which is useful for later analysis.
-- Formula: DISTICNT [Dimension]

-- Task: Explore all countries the customers come from
SELECT DISTINCT
country
FROM Gold.dim_customers

-- Task: Explore all product categories 'Major Divisions', subcategories and name
SELECT DISTINCT
category,
subcategory,
product_name
FROM Gold.dim_products
ORDER BY 1,2,3

-- 3) Date Exploration
-- Identifying the earliest and latest dates (boundaries)
-- Understanding the scope of data and the timespan
-- Formula: MIN/MAX [Date Dimension]

-- Task: Find the date of the first and last order
SELECT
MIN(order_date) AS First_Order_Date,
MAX(order_date) AS Last_Order_Date
FROM Gold.fact_sales

-- Task: Find the timespan of sales across years
SELECT
DATEDIFF(YEAR,MIN(order_date),MAX(order_date)) AS 'Orders Range in Years'
FROM Gold.fact_sales

-- Find the youngest and oldest customers and calculate their ages
SELECT
MIN(birth_date) AS Birth_date,
DATEDIFF(YEAR,MIN(birth_date),GETDATE()) AS Age
FROM Gold.dim_customers
UNION ALL
SELECT
MAX(birth_date) AS Birth_Date,
DATEDIFF(YEAR,MAX(birth_date),GETDATE())
FROM Gold.dim_customers

-- 4) Measures Exploration
-- Calculate the key metric of the business (Highest level of Aggregation | Lowest level of Details)
-- Formula: AggFunc [Measure]

-- Task: Find the Total Sales
SELECT
SUM(sales_amount) AS Total_Sales
FROM Gold.fact_sales

-- Task: Find how many items are sold
SELECT
SUM(quantity) AS Total_Items_Sold
FROM Gold.fact_sales

-- Task: Find the average selling price
SELECT
AVG(price) AS Avg_Sales
FROM Gold.fact_sales

-- Find the total number of order
SELECT
COUNT(order_number) AS Total_Orders_Number
FROM Gold.fact_sales

SELECT
COUNT(DISTINCT order_number) AS Total_Orders_Number
FROM Gold.fact_sales

-- Find the total number of products
SELECT
COUNT(product_name) AS Total_Products
FROM Gold.dim_products

SELECT
COUNT(DISTINCT product_name) AS Total_Products
FROM Gold.dim_products

-- Find the total number of customers
SELECT 
COUNT(customer_key) AS Total_Customers
FROM Gold.dim_customers

SELECT 
COUNT(DISTINCT customer_key) AS Total_Customers
FROM Gold.dim_customers

-- Find the total number of customers that has placed an order
SELECT 
COUNT(DISTINCT customer_key) AS Total_Customers
FROM Gold.fact_sales

-- Generate a report that shows all key metrics of the business
SELECT
'Total Sales' AS Measure_Name, 
SUM(sales_amount) AS Measure_Value
FROM Gold.fact_sales

UNION ALL

SELECT
'Total Items',
SUM(quantity) 
FROM Gold.fact_sales

UNION ALL

SELECT
'Average Sales',
AVG(price)
FROM Gold.fact_sales

UNION ALL

SELECT
'Total Orders Number',
COUNT(DISTINCT order_number) 
FROM Gold.fact_sales

UNION ALL

SELECT
'Total Products Number',
COUNT(product_name)
FROM Gold.dim_products

UNION ALL

SELECT 
'Total Customers Number',
COUNT(customer_key)
FROM Gold.dim_customers

-- 5) Magnitude Analysis
-- Comparing the measure values by categories
-- It helps in understanding the importance of different categories
-- Formula: Agg Func [Measure] By [Dimension] -> Total [Sales] By [Country]

SELECT * FROM Gold.dim_customers
SELECT * FROM Gold.dim_products
SELECT * FROM Gold.fact_sales

-- Task: Find the total customers by country
SELECT 
country,
COUNT(customer_key)
FROM Gold.dim_customers
GROUP BY country
ORDER BY COUNT(customer_key) DESC

-- Task: Find the total customers by gender
SELECT
gender,
COUNT(customer_key)
FROM Gold.dim_customers
GROUP BY gender
ORDER BY COUNT(customer_key) DESC 

-- Task: Find the total products by category
SELECT 
category,
COUNT(DISTINCT product_name)
FROM Gold.dim_products
GROUP BY category
ORDER BY COUNT(DISTINCT product_name) DESC

-- What is the average cost in each category?
SELECT 
category,
AVG(product_cost)
FROM Gold.dim_products
GROUP BY category
ORDER BY AVG(product_cost) DESC

-- What is the total revenue generated in each category?
SELECT
p.category,
SUM(f.sales_amount)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.category
ORDER BY SUM(f.sales_amount) DESC

-- Find the total revenue generated by each customer
SELECT
CONCAT(c.first_name,' ',c.last_name),
SUM(f.sales_amount)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY CONCAT(c.first_name,' ',c.last_name) 
ORDER BY SUM(f.sales_amount) DESC

-- What is the distribution of sold items across countries?
SELECT
c.country,
SUM(f.quantity)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY c.country
ORDER BY SUM(f.quantity) DESC

-- Low Cardinality Dimensions: Dimensions with low number of unique values  
-- High Cardinality Dimensions: Dimensions with high number of unique values

-- 6) Ranking (Top N - Bottom N)
-- Order the values of dimensions by measure (Top N Performers | Bottom N Performers)
-- Formula: Rank [Dimension] By AggFunc [Measure] -> Top 5 Products By Total Sales

-- Task: Which 5 products generate the highest revenue? 
SELECT TOP 5
p.product_name,
SUM(f.sales_amount)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY SUM(f.sales_amount) DESC

-- Solving it using a Window Function (Better for more complex queries)
SELECT
*
FROM
(
	SELECT 
	p.product_name,
	SUM(f.sales_amount) total_revenue,
	ROW_NUMBER() OVER (ORDER BY SUM(f.sales_amount) DESC) AS Rank_Products
	FROM Gold.fact_sales f
	LEFT JOIN Gold.dim_products p
	ON f.product_key = p.product_key
	GROUP BY p.product_name
) t 
WHERE Rank_Products <= 5

-- Task: What are the 5 worst-performing products in terms of sales? 
SELECT TOP 5
p.product_name,
SUM(f.sales_amount)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_products p
ON f.product_key = p.product_key
GROUP BY p.product_name
ORDER BY SUM(f.sales_amount)

-- Task: Find the top 10 customers who have generated the highest revenue and 3 customers with the fewest orders placed
-- Top 10 cutomers with highest revenue
SELECT TOP 10
CONCAT(c.first_name,' ', c.last_name),
SUM(f.sales_amount)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY CONCAT(c.first_name,' ', c.last_name)
ORDER BY SUM(f.sales_amount) DESC 
-- The 3 customers with the fewest orders placed
SELECT TOP 3
CONCAT(c.first_name,' ', c.last_name),
COUNT(DISTINCT order_number)
FROM Gold.fact_sales f
LEFT JOIN Gold.dim_customers c
ON f.customer_key = c.customer_key
GROUP BY CONCAT(c.first_name,' ', c.last_name)
ORDER BY COUNT(DISTINCT order_number)
